wav_clean_root: /mnt/inspurfs/home/wangpengyu/dataset/wsj0/si_et_05
wav_save_root: /mnt/inspurfs/home/wangpengyu/RVAE-EM/data/wavs/test
sample_rate: 16000
spch_len: 5.104

RIR_save_root: /mnt/inspurfs/home/wangpengyu/RVAE-EM/data/rirs/test
T60_range: [0.4,1]
room_sz_range: [5,15,5,15,2,6]
min_distance_to_wall: 1
num_RIRs: 300
random_seed: 42